/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_video_trimmer_natives_VideoTrimmer */

#ifndef _Included_net_video_trimmer_natives_VideoTrimmer
#define _Included_net_video_trimmer_natives_VideoTrimmer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_video_trimmer_natives_VideoTrimmer
 * Method:    trim
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_net_video_trimmer_natives_VideoTrimmer_trim
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
